// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PlaceList$ReactTemplate = require("./PlaceList.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, PlaceList$ReactTemplate.make(/* array */[])), "root");

/*  Not a pure module */
