// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Data$ReactTemplate = require("./Data.bs.js");
var Phone$ReactTemplate = require("./Phone.bs.js");

var component = ReasonReact.statelessComponent("PlaceList-ReactTemplate");

function s(prim) {
  return prim;
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("ul", undefined, Belt_Array.map($$Array.of_list(Data$ReactTemplate.places), (function (place) {
                                    var match = place[/* image */3][/* attributionUrl */2];
                                    return React.createElement("li", {
                                                key: place[/* id */0]
                                              }, React.createElement("div", undefined, place[/* name */1]), React.createElement("img", {
                                                    alt: place[/* name */1],
                                                    src: place[/* image */3][/* url */0]
                                                  }), match !== undefined ? React.createElement("a", {
                                                      href: match
                                                    }, place[/* image */3][/* attribution */1]) : React.createElement("p", undefined, place[/* image */3][/* attribution */1]), ReasonReact.element(undefined, undefined, Phone$ReactTemplate.make(place[/* phone */5], /* array */[])));
                                  }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.s = s;
exports.make = make;
/* component Not a pure module */
